name: staging

on:
  push:
    branches: [ "staging" ]

jobs:
  Build_and_Push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB

    steps:
      - uses: actions/checkout@v4

      - name: npm install and build
        run: |
          composer update
          composer install
          npm install
          npm run build

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/pentastix:dashboard-${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/pentastix:dashboard-latest \
            .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pentastix:dashboard-${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pentastix:dashboard-latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Build_and_Push
    environment: VM

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            /home/ubuntu/event-dashboard/deploy.sh
